language: ruby

rvm:
 - 2.2.1

# Adapted from https://github.com/iblancasa/blog_files/blob/master/.travis.yml
before_install:
  - sudo apt-get update
  - sudo apt-get install -y git
  - gem install bundler
  - bundle install
  - git config --global user.email "dgiimblog@gmail.com"
  - git config --global user.name "dgiimbot"
  - echo ${TUX_KEY} > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo ${KNOWN_HOST_RSA} >> ~/.ssh/known_hosts
  - |
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && git clone -b master "${TUX_REPO}" _site # && rm -rf _site/*

script: "bundle exec jekyll build"

after_script:
  - cd _site/
  - |
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && (git ls-files --deleted -z | xargs -0 git rm) && \
    git add * && \
    git add . && \
    git commit -m "`date`" && \
    git push origin master --quiet

branches:
  only:
    - gh-pages
