language: ruby

rvm:
 - 2.3.1

# Adapted from https://github.com/iblancasa/blog_files/blob/master/.travis.yml
before_install:

script: "bundle exec jekyll build --config _config.yml"

after_script:

branches:
  only:
    - site
