
# Github defaults
# safe: true
lsi: false

# Settings
baseurl: /blog
name: libreim
title: LibreIM
description: Blog de la comunidad LibreIM
url: http://libreim.github.io/blog

markdown: kramdown
kramdown:
  parse_span_html: false
highlighter: rouge

# Dependencies
gems:
  - jemoji
  - octopress-paginate
  - jekyll-gist
#  - jekyll-mentions

permalink: /:year/:month/:day/:title/
# paginate: 5
# paginate_path: "/page/:num/"
# Configure octopress-paginate:
pagination:
  per_page: 5
  limit: false
  permalink: /page/:num/
  title_suffix: ""

excerpt_separator: "<!--more-->"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile

# Autores
authors:
  fdavidcl:
    name: David Charte
    github: fdavidcl
  M42:
    name: Mario Román
    github: M42
  pbaeyens:
    name: Pablo Baeyens
    github: pbaeyens
  ncordon:
    name: Ignacio Cordón
    github: NCordon
  andreshp:
    name: Andrés Herrera Poyatos
    github: andreshp
  oxcar:
    name: Óscar Bermúdez
    github: oxcar103
  jj:
    name: Juan Julián Merelo
    github: JJ
  makixun:
    name: Miguel Anguita
    github: makixun
  #jcentrena:
  #  name: José Carlos Entrena
  #  github: JCEntrena
  fjsaezm:
    name: Javier Sáez
    github: fjsaezm
  jmml97:
    name: José María Martín
    github: jmml97
  danipozodg:
    name: Daniel Pozo
    github: danipozodg
  antcc:
    name: Antonio Coín
    github: antcc
  ludvins:
    name: Luis Ortega
    github: ludvins

#nav_list:
# Inicio: '/'
# Archivo: '/archive'
