# Github defaults:
# safe: true
# lsi: false
# pygments: true

# Settings
baseurl: /blog
name: Doble Grado en Ingeniería Informática y Matemáticas
description: Blog de los alumnos del Doble Grado en Ingeniería Informática y Matemáticas de la Universidad de Granada
url: http://dgiim.github.io/blog/

markdown: kramdown
kramdown:
  parse_span_html: false

permalink: /:year/:month/:day/:title
paginate: 4
paginate_path: /p/:num

collections:
  math_resources:
    output: true
    permalink: /resources/m/:path/
  cs_resources:
    output: true
    permalink: /resources/cs/:path/


# Autores
authors:
  fdavidcl:
    name: David Charte
    github: fdavidcl
  mario:
    name: Mario Román
    github: M42
  oxcar:
    name: Óscar Bermúdez
    github: oxcar103
  jcentrena:
    name: José Carlos Entrena
    github: JCEntrena
  pbaeyens:
    name: Pablo Baeyens
    github: pbaeyens

#nav_list:
# Inicio: '/'
# Archivo: '/archive'
